#CREACION DE BASE DE DATOS
CREATE DATABASE db_pias CHARACTER SET utf8 COLLATE utf8_spanish2_ci;

#CREACION DE USUARIO
CREATE USER 'usr_pias'@'localhost' IDENTIFIED BY 'pass_pias';

#ASIGANACION DE PRIVILEGIOS A USUARIO SOBRE BASE DE DATOS
GRANT ALL PRIVILEGES ON db_pias.* TO 'usr_pias'@'localhost';
FLUSH PRIVILEGES;